const express = require("express")
const {filterUser,ageCat,getCity,getGender,community,getProfile}= require("../controller/profile")
const routerProfile = express.Router()
routerProfile.get('/filterUser',filterUser)
routerProfile.get('/ageGet',ageCat)
routerProfile.get('/getcity',getCity)
routerProfile.get('/getgender',getGender)
routerProfile.get("/community",community)
routerProfile.get("/getProfile/:id",getProfile)
module.exports = routerProfile